### ISSUE TITLE
Hot reload update view

### ISSUE THREAD

**Issue by challenger532** [ds300/react-native-typescript-transformer#34] opened 2017-12-06 12:17 UTC
Hot reload is not updating the views! A Toast with hot load is shown but views are not updated, on force refresh, the simulator views are updating!
![screenshot from 2017-12-06 14-15-27](https://user-images.githubusercontent.com/6458536/33661318-1008aade-da90-11e7-8a74-6af64b6520f0.png)

**Comment by a9udn9u** [comment] 2018-02-27 07:33
I'm having the same issue on macOS.

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": "./src",
    "strict": true,
    "target": "es6",
    "module": "es6",
    "moduleResolution": "node",
    "noEmit": true,
    "jsx": "react",
    "lib": [ "dom", "es6", "es2015", "es2016" ]
  },
  "include": [ "src/**/*.ts", "src/**/*.tsx" ]
}
```

Since `tsc` doesn't emit any output, I have to restart the packager on every file change, it's quite annoying.

**Comment by ds300** [comment] 2018-05-25 15:16
I'm going to close this issue due to inactivity. If you're still having trouble with hot reloading, please feel free to open another issue and link to this one :pray:

**Comment by jas99** [comment] 2018-06-05 14:41
yup still happening

**Comment by ds300** [comment] 2018-06-05 15:59
Any chance you could reproduce this issue in a public repo?

**Comment by jas99** [comment] 2018-06-05 16:02
yea lemme do it :)

**Comment by jas99** [comment] 2018-06-05 17:02
Thr you go 
https://github.com/jas99/rn_ts_hmr_issue_34

**Comment by ds300** [comment] 2018-06-05 17:04
Dope thanks! I'll look at this later tonight.

**Comment by jas99** [comment] 2018-06-05 17:04
@ds300 

Although also tried https://www.npmjs.com/package/react-native-template-typescript.

Lemme attach my envs
```
envinfo                                                                                     10.38   ✔   22:27    05.06.18

  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 4.90 GB / 16.00 GB
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.3.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.11.3 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.17.1 - /usr/local/bin/git
  Servers:
    Apache: 2.4.29 - /usr/sbin/apachectl
  Virtualization:
    Docker: 18.05.0 - /usr/local/bin/docker
    VirtualBox: 5.2.10 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    Android SDK:
      Build Tools: 23.0.1, 26.0.2, 27.0.3
      API Levels: 23, 26, 27
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.0 - /usr/bin/vim
    VSCode: 1.23.1 - /usr/local/bin/code
    Xcode: 9.3/9E145 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.10.2 - /usr/local/bin/go
    Java: 1.8.0 - /usr/bin/javac
    Perl: 5.18.2 - /usr/bin/perl
    PHP: 7.1.14 - /usr/bin/php
    Python: 2.7.15 - /usr/local/bin/python
    Ruby: 2.5.1 - /usr/local/bin/ruby
    Rust: 1.9.0 - /Users/jas/.cargo/bin/rustup
  Databases:
    SQLite: 3.19.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 66.0.3359.181
    Firefox: 59.0.2
    Safari: 11.1
```

**Comment by jas99** [comment] 2018-06-05 17:07
Basically once I change code, on my device it gives me toast msg of hmr update and then disappears without making any updates.

Lemme know if you need more info.

**Comment by ds300** [comment] 2018-06-05 17:09
Just double checking: hot reloading works ok if you use the standard non-typescript setup?

**Comment by jas99** [comment] 2018-06-05 17:28
It definitely does.

**Comment by ds300** [comment] 2018-06-05 19:53
This fixed it for me: tsconfig.json

```diff
 {
   "compilerOptions": {
     /* Basic Options */
-    "target": "es5",
+    "target": "es2015",
-    "module": "commonjs",
+    "module": "es2015",
     // "lib": [],                             /* Specify library files to be included in the compilation. */
     // "allowJs": true,                       /* Allow javascript files to be compiled. */
 ...
```

**Comment by jas99** [comment] 2018-06-06 06:27
Thx very much for your time, it worked for me as well 😄. 
Feel free to close it.

**Closed** 2018-06-06 07:30 UTC

**Comment by jas99** [comment] 2018-06-06 14:11
For anybody else stumbling on it; HMR also don't work with `"jsx": "react-native"`, it need to be `"jsx": "react"`

Thx

**Comment by ifiokjr** [comment] 2018-06-19 13:37
@ds300 you sir are a legend amongst us mere mortals! If you haven't guessed... your fix worked for me. 

Another suggestion for those who are still seeing crashes with Hot Module Reloading when using React Native in a Typescript environment; make sure to get rid of any circular dependencies. 

A great library for helping with this is [tslint-no-circular-imports](https://github.com/bcherny/tslint-no-circular-imports).

**Comment by ifiokjr** [comment] 2018-09-30 06:48
@ykensuke that looks like a different issue. 

There are two potential fixes. Either import firebase as follows:

```ts
import * as firebase from 'react-native-firebase'
```

Or, perhaps easier, update your tsconfig.json to include the following two properties.

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
	...
  },
}
```

It looks like
