### ISSUE TITLE
Getting: bundling failed: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by eassymo** [ds300/react-native-typescript-transformer#36] opened 2017-12-18 18:37 UTC
I'm getting: 

bundling failed: TypeError: Cannot read property 'replace' of undefined

when 

> Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.

Enviroment:

    "react": "16.0.0",
    "react-native": "0.51.0",
    "metro-bundler": "^0.22.1",
    "react-native-typescript-transformer": "^1.1.4",
    "typescript": "~2.3.4"

**Comment by ds300** [comment] 2017-12-18 21:51
There's not much info to go on here. react-native-typescript-transformer doesn't use a `.replace` method anywhere directly. Can you provide a repository which reproduces the issue, by any chance?

**Comment by jkbreunig** [comment] 2017-12-28 02:57
react-native 0.52.0-rc.0
source-map-consumer.js 
bundling failed: TypeError: Cannot read property 'sections' of undefined

function SourceMapConsumer(aSourceMap) {
  var sourceMap = aSourceMap;
  if (typeof aSourceMap === 'string') {
    sourceMap = JSON.parse(aSourceMap.replace(/^\)\]\}'/, ''));
  }

  return sourceMap.sections != null
    ? new IndexedSourceMapConsumer(sourceMap)
    : new BasicSourceMapConsumer(sourceMap);

**Comment by shroukkhan** [comment] 2018-05-25 04:38
@ds300 it happens with latest version of the boilerplate. basically i tried this:

`ignite new OKKAMI3 --b ignite-typescript-boilerplate --min`

it all went well, but as soon as i start the packager :

` ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running Metro Bundler on port 8081.                                       │
 │                                                                            │
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own Metro Bundler  instance if you    │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/shroukkhan/works/OKKAMI3


Metro Bundler ready.

Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: TypeError: Cannot read property 'replace' of undefined
    at asyncify (/Users/shroukkhan/works/OKKAMI3/node_modules/metro-bundler/src/JSTransformer/worker/index.js:141:16)
    at /Users/shroukkhan/works/OKKAMI3/node_modules/async/asyncify.js:82:27
    at /Users/shroukkhan/works/OKKAMI3/node_modules/async/internal/initialParams.js:11:12
    at exports.transformAndExtractDependencies (/Users/shroukkhan/works/OKKAMI3/node_modules/metro-bundler/src/JSTransformer/worker/index.js:178:3)
    at handle (/Users/shroukkhan/works/OKKAMI3/node_modules/metro-bundler/src/worker-farm/lib/child/index.js:50:8)
    at process.<anonymous> (/Users/shroukkhan/works/OKKAMI3/node_modules/metro-bundler/src/worker-farm/lib/child/index.js:56:3)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)`

**Comment by ds300** [comment] 2018-05-25 15:19
I'm going to close this issue due to inactivity. If you're still having trouble with bundling, please feel free to open another issue and link to this one :pray:

**Closed by ds300** 2018-05-25 15:19 UTC
